### ISSUE TITLE
EmailBuilder

### ISSUE THREAD

**Issue by odesyatnyk** [nmakhmutov/Elwark.People#54]
Hey, i was inspired by your implementation of usage Fluid to render emails, thanks for great example!
However i noticed a potential bug here, that sometimes `StreamWriter` does not flushes whole text into memory stream and resulted template is incomplete, so before converting `MemoryStream` to array i had to manually execute `sw.Flush()`

idk if it has anything to do with my machine, but i'm running on macos, M2, net6

hope this helps :)

https://github.com/nmakhmutov/Elwark.People/blob/3c8c82957da02a168f923bad30271a80b669959f/src/People.Api/Infrastructure/EmailBuilder/EmailBuilder.cs#L22

**Comment by nmakhmutov** [comment]
Hi!
Yea, you are right but better way it is replace `StreamWriter` to `StringWriter`. Eventually template is a string and it possible to use only `StringWriter`. 

If you are interesting in it, check my chenges 
https://github.com/nmakhmutov/Elwark.People/blob/f9462656e55d09efff0a7b62ed8a9dea9a4aceb5/src/People.Api/Infrastructure/EmailBuilder/EmailBuilder.cs#L14

**Comment by odesyatnyk** [comment]
great idea, thank you!
